-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Create 'profiles' table
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  dob date,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create 'listings' table
create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null,
  area numeric not null,
  address text not null,
  bedroom_count int not null,
  image_url text,
  is_visible boolean default true,
  user_id uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create 'comments' table
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  content text not null,
  -- rating column will be added safely below if it doesn't exist
  listing_id bigint references public.listings(id) on delete cascade not null,
  user_id uuid references public.profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Safely add rating column if it doesn't exist
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'comments' and column_name = 'rating') then
        alter table public.comments add column rating int default 0 check (rating >= 0 and rating <= 5);
    end if;
end $$;

-- 4. Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.listings enable row level security;
alter table public.comments enable row level security;

-- 5. Create Policies (Drop first to avoid errors on re-run)

-- Profiles
drop policy if exists "Public profiles are viewable by everyone." on public.profiles;
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

drop policy if exists "Users can update own profile." on public.profiles;
create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Listings
drop policy if exists "Listings are viewable by everyone." on public.listings;
create policy "Listings are viewable by everyone."
  on public.listings for select
  using ( is_visible = true );

drop policy if exists "Users can insert their own listings." on public.listings;
create policy "Users can insert their own listings."
  on public.listings for insert
  with check ( auth.uid() = user_id );

drop policy if exists "Users can update their own listings." on public.listings;
create policy "Users can update their own listings."
  on public.listings for update
  using ( auth.uid() = user_id );

-- Comments
drop policy if exists "Comments are viewable by everyone." on public.comments;
create policy "Comments are viewable by everyone."
  on public.comments for select
  using ( true );

drop policy if exists "Authenticated users can insert comments." on public.comments;
create policy "Authenticated users can insert comments."
  on public.comments for insert
  with check ( auth.role() = 'authenticated' );

-- 6. Create Trigger for New User Registration
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, dob, role)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    (new.raw_user_meta_data->>'dob')::date,
    coalesce(new.raw_user_meta_data->>'role', 'user')
  );
  return new;
end;
$$;

-- Drop trigger if exists to avoid error
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
